In [2]:
import os
import torch
import numpy as np
import math

In [3]:
A = torch.rand(3, 3, requires_grad=True)
B = torch.rand(3, 3)

C = torch.matmul(A, B)

C.backward(torch.ones_like(C))

print("Gradient of A:\n", A.grad)

Gradient of A:
 tensor([[1.9154, 1.4143, 1.4832],
        [1.9154, 1.4143, 1.4832],
        [1.9154, 1.4143, 1.4832]])


In [4]:
tensor1 = torch.rand(3, 1)
tensor2 = torch.rand(1, 3)

broadcast_result = tensor1 + tensor2
C = torch.rand(3, 3)
result = broadcast_result * C

print("Result of broadcasting:\n", result)


Result of broadcasting:
 tensor([[0.2878, 0.2303, 1.0306],
        [0.7752, 0.5141, 0.7098],
        [1.1578, 0.1213, 0.1295]])


In [5]:
tensor = torch.rand(6, 4)

reshaped_tensor = tensor.view(3, 8)

sliced_tensor = reshaped_tensor[:, :2]

print("Reshaped Tensor:\n", reshaped_tensor)
print("Sliced Tensor (first two columns):\n", sliced_tensor)

Reshaped Tensor:
 tensor([[0.6867, 0.1455, 0.2914, 0.4062, 0.4519, 0.3375, 0.3057, 0.1272],
        [0.3241, 0.4159, 0.0940, 0.6696, 0.0285, 0.3075, 0.6592, 0.4100],
        [0.5532, 0.2526, 0.9518, 0.4777, 0.4413, 0.6545, 0.0851, 0.6175]])
Sliced Tensor (first two columns):
 tensor([[0.6867, 0.1455],
        [0.3241, 0.4159],
        [0.5532, 0.2526]])


In [6]:
np_array = np.random.rand(3, 3)

torch_tensor = torch.from_numpy(np_array)

modified_tensor = torch_tensor * 3

modified_np_array = modified_tensor.numpy()

print("Original NumPy array:\n", np_array)
print("Modified NumPy array:\n", modified_np_array)

Original NumPy array:
 [[0.81510163 0.06741678 0.41055477]
 [0.52160294 0.15101118 0.87421675]
 [0.61751022 0.62603212 0.04549932]]
Modified NumPy array:
 [[2.4453049  0.20225035 1.23166432]
 [1.56480883 0.45303353 2.62265025]
 [1.85253067 1.87809637 0.13649796]]


In [7]:
tensor_uniform = torch.rand(5, 5)

tensor_normal = torch.randn(5, 5)

elementwise_product = tensor_uniform * tensor_normal

mean_val = elementwise_product.mean()
std_val = elementwise_product.std()

reshaped_tensor = elementwise_product.view(25)
sum_val = reshaped_tensor.sum()

print("Mean of result tensor:", mean_val.item())
print("Standard deviation of result tensor:", std_val.item())
print("Sum of all elements:", sum_val.item())


Mean of result tensor: 0.21654795110225677
Standard deviation of result tensor: 0.4809201955795288
Sum of all elements: 5.413698673248291


## Exercise 4

In [8]:


def sigmoid_math(x):
    return 1 / (1 + math.exp(-x))

def sigmoid_np(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_grad(x):
    s = sigmoid_np(x)
    return s * (1 - s)

def image2vector(image):
    return image.reshape(-1, 1)

def normalizeRows(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

def L1_loss(y_hat, y):
    return np.sum(np.abs(y_hat - y))

def L2_loss(y_hat, y):
    return np.sum((y_hat - y) ** 2)

x = 1.5
image = np.random.rand(3, 3, 3)
y_hat = np.array([0.9, 0.2, 0.4])
y = np.array([1.0, 0.0, 0.5])
matrix_x = np.array([[4, 3], [1, 2]])

print("Sigmoid using math.exp:", sigmoid_math(x))
print("Sigmoid using np.exp:", sigmoid_np(x))
print("Sigmoid gradient:", sigmoid_grad(x))
print("Image to vector:", image2vector(image))
print("Normalized rows:\n", normalizeRows(matrix_x))
print("L1 Loss:", L1_loss(y_hat, y))
print("L2 Loss:", L2_loss(y_hat, y))


Sigmoid using math.exp: 0.8175744761936437
Sigmoid using np.exp: 0.8175744761936437
Sigmoid gradient: 0.14914645207033286
Image to vector: [[0.91173213]
 [0.19458769]
 [0.93182039]
 [0.95519283]
 [0.45597187]
 [0.40021271]
 [0.08285124]
 [0.12403379]
 [0.00764217]
 [0.10423339]
 [0.7420208 ]
 [0.78356137]
 [0.97471311]
 [0.19939569]
 [0.98971015]
 [0.20916595]
 [0.63287879]
 [0.8944908 ]
 [0.08551047]
 [0.12795883]
 [0.02931203]
 [0.41948011]
 [0.77873947]
 [0.75730488]
 [0.1394369 ]
 [0.56808706]
 [0.80657715]]
Normalized rows:
 [[0.8        0.6       ]
 [0.4472136  0.89442719]]
L1 Loss: 0.39999999999999997
L2 Loss: 0.06


## Exercise 5