In [2]:
import os
import torch
import numpy as np

In [3]:
A = torch.rand(3, 3, requires_grad=True)
B = torch.rand(3, 3)

C = torch.matmul(A, B)

C.backward(torch.ones_like(C))

print("Gradient of A:\n", A.grad)

Gradient of A:
 tensor([[1.2239, 1.3456, 2.1941],
        [1.2239, 1.3456, 2.1941],
        [1.2239, 1.3456, 2.1941]])


In [4]:
tensor1 = torch.rand(3, 1)
tensor2 = torch.rand(1, 3)

broadcast_result = tensor1 + tensor2
C = torch.rand(3, 3)
result = broadcast_result * C

print("Result of broadcasting:\n", result)


Result of broadcasting:
 tensor([[0.7522, 0.4662, 0.4413],
        [0.3360, 0.5917, 0.3255],
        [0.6344, 0.0595, 0.0124]])


In [5]:
tensor = torch.rand(6, 4)

reshaped_tensor = tensor.view(3, 8)

sliced_tensor = reshaped_tensor[:, :2]

print("Reshaped Tensor:\n", reshaped_tensor)
print("Sliced Tensor (first two columns):\n", sliced_tensor)

Reshaped Tensor:
 tensor([[0.5719, 0.4697, 0.6739, 0.9811, 0.2934, 0.5532, 0.9918, 0.8680],
        [0.2103, 0.4093, 0.2537, 0.5129, 0.2786, 0.3683, 0.2729, 0.6610],
        [0.4028, 0.2638, 0.9629, 0.5513, 0.9738, 0.6731, 0.6569, 0.2678]])
Sliced Tensor (first two columns):
 tensor([[0.5719, 0.4697],
        [0.2103, 0.4093],
        [0.4028, 0.2638]])


In [6]:
np_array = np.random.rand(3, 3)

torch_tensor = torch.from_numpy(np_array)

modified_tensor = torch_tensor * 3

modified_np_array = modified_tensor.numpy()

print("Original NumPy array:\n", np_array)
print("Modified NumPy array:\n", modified_np_array)

Original NumPy array:
 [[0.13291879 0.75482448 0.02655239]
 [0.21699198 0.25919541 0.74300164]
 [0.94897842 0.86809073 0.541048  ]]
Modified NumPy array:
 [[0.39875637 2.26447344 0.07965716]
 [0.65097594 0.77758624 2.22900492]
 [2.84693527 2.6042722  1.62314401]]


In [7]:
# Initialize a 5x5 tensor with random values from uniform distribution [0, 1]
tensor_uniform = torch.rand(5, 5)

# Initialize another 5x5 tensor with values from normal distribution (mean=0, std=1)
tensor_normal = torch.randn(5, 5)

# Element-wise multiplication
elementwise_product = tensor_uniform * tensor_normal

# Compute the mean and standard deviation
mean_val = elementwise_product.mean()
std_val = elementwise_product.std()

# Reshape to a 1D tensor of size 25
reshaped_tensor = elementwise_product.view(25)

# Compute the sum of all elements
sum_val = reshaped_tensor.sum()

print("Mean of result tensor:", mean_val.item())
print("Standard deviation of result tensor:", std_val.item())
print("Sum of all elements:", sum_val.item())


Mean of result tensor: -0.086939737200737
Standard deviation of result tensor: 0.6397203803062439
Sum of all elements: -2.1734933853149414


In [8]:
import math
import numpy as np

def sigmoid_math(x):
    return 1 / (1 + math.exp(-x))

def sigmoid_np(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_grad(x):
    s = sigmoid_np(x)
    return s * (1 - s)

def image2vector(image):
    return image.reshape(-1, 1)

def normalizeRows(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

def L1_loss(y_hat, y):
    return np.sum(np.abs(y_hat - y))

def L2_loss(y_hat, y):
    return np.sum((y_hat - y) ** 2)

x = 1.5
image = np.random.rand(3, 3, 3)
y_hat = np.array([0.9, 0.2, 0.4])
y = np.array([1.0, 0.0, 0.5])
matrix_x = np.array([[4, 3], [1, 2]])

print("Sigmoid using math.exp:", sigmoid_math(x))
print("Sigmoid using np.exp:", sigmoid_np(x))
print("Sigmoid gradient:", sigmoid_grad(x))
print("Image to vector:", image2vector(image))
print("Normalized rows:\n", normalizeRows(matrix_x))
print("L1 Loss:", L1_loss(y_hat, y))
print("L2 Loss:", L2_loss(y_hat, y))


Sigmoid using math.exp: 0.8175744761936437
Sigmoid using np.exp: 0.8175744761936437
Sigmoid gradient: 0.14914645207033286
Image to vector: [[0.85937134]
 [0.52473629]
 [0.27516372]
 [0.68460937]
 [0.3240754 ]
 [0.58145172]
 [0.34427875]
 [0.45498018]
 [0.08015113]
 [0.02956836]
 [0.64605939]
 [0.55030387]
 [0.01737811]
 [0.09210763]
 [0.47340493]
 [0.73660467]
 [0.18059885]
 [0.67709266]
 [0.57053532]
 [0.45614297]
 [0.29888311]
 [0.27032953]
 [0.96546595]
 [0.80060923]
 [0.34842866]
 [0.12095699]
 [0.53264767]]
Normalized rows:
 [[0.8        0.6       ]
 [0.4472136  0.89442719]]
L1 Loss: 0.39999999999999997
L2 Loss: 0.06
